[tools]
bun = "1.4.2"

[tasks.link]
description = "Exécute le script global pour symlinker la config nginx locale."
depends = ["nginx-link"]

[tasks.unlink]
description = "Exécute le script global pour supprimer le symlink de la config nginx locale."
depends = ["nginx-unlink"]

[tasks.dev]
description = "Link nginx + vérifie caddy + démarre le serveur de dev Astro"
depends = ["link", "caddy-check"]
run = "bun run dev"

[tasks.build]
description = "Installe les dépendances (frozen-lockfile) et build le site"
run = "bun install --frozen-lockfile && bun run build"

[tasks.preview]
description = "démarre une prévisualisation locale du build"
run = "bun run preview"

[tasks.net-build]
description = "build via l'outil netlify-cli"
run = "bunx netlify-cli build"

[tasks.net-preview]
description = "démarre une prévisualisation locale du build fait par net-build"
run = "bunx netlify-cli serve"